### ISSUE TITLE
TypeError: $(...).masonry is not a function

### ISSUE THREAD

**Issue by noscript** [desandro/jquery-bridget#12]
I'm trying to make masonry + jquery-bridget +  ["Include only jQuery parts you need"](https://alexomara.com/blog/webpack-and-jquery-include-only-the-parts-you-need/) working like so:

```js
var $ = require('jquery/src/core');
var jQueryBridget = require('jquery-bridget');
var Masonry = require('masonry-layout');
jQueryBridget('masonry', Masonry, $);

$('.grid').masonry({
  itemSelector: '.grid-item',
});
```
and getting `TypeError: $(...).masonry is not a function`.

I tried to figure out what other jQuery modules are required but no luck. Is including entire jQuery necessary for jquery-bridget to work?

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm not exactly sure what is and is not included in jQuery's `core`. This should work in there, as jQuery Bridget only adds `.masonry` to jQuery's `fn` namespace, thus making it a plugin.

One way around this is to remove jQuery plugin functionality and just use Masonry as a vanilla JS API.

**Comment by noscript** [comment]
I went with vanilla for now, but bridget wrapper looks certainly prettier :)
