### ISSUE TITLE
Webpack vendor.js filesize skyrockets

### ISSUE THREAD

**Issue by ogierschelvis** [desandro/jquery-bridget#13]
Hi,

I am using Laravel Mix 2.1.14  with babel to compile my assets which depends on Webpack 3.
I have splitted my code into a vendor.min.js and app.min.js. My project uses Flickity so I needed to use `jquery-bridget` to make it available as jQuery plugin.

I thought: "Oh well another 2 KB (the filesize of the main js file) can't hurt." But soon after compiling my assets I found out this move added a whopping 88 KB to my vendor.min.js file.

Possibly this can be because jquery-bridget comes with its own version of jQuery.
But I already had that as a separate dependency.
I've worked around this by adding the source of the file directly into my js file and it works, but maybe it would be nice if a fix for this would be fabricated, because it boils down to an overhead of roughly 4000% just to include 2 KB of javascript.

**Comment by desandro** [comment]
As you mention, if you already have another version of jQuery in your build chain, then you'll need to add a fix to prevent the version of jQuery that jQuery Bridget will add via its dependencies. But jQuery Bridget needs jQuery as a dependency. That's how it all works 😝

**Comment by ogierschelvis** [comment]
Aha. Sorry about this. As I was browsing StackOverflow I found out this is a more common problem when dealing with Webpack and duplicate dependencies.
