### ISSUE TITLE
Getting TypeError: $.bridget is not a function

### ISSUE THREAD

**Issue by pabeln** [desandro/jquery-bridget#6]
Installed both Isotope & jQuery-bridget via npm and am using Browserify. I get no build errors but when I run the code I get a `$.bridget is not a function` error. I've doublechecked the built file and all the required code is in there. 

this is the code in my module:

```javascript
var $ = require('jquery');
var Isotope = require('isotope-layout');
var bridget = require('jquery-bridget');
$.bridget( 'isotope', Isotope );

function init () {
	$newsgrid = $('#news-grid');
 	$newsgrid.isotope({
		itemSelector: '.col-md-4'
	});
}
````

Any ideas why this is happening? Bug? Thanks.

**Comment by desandro** [comment]
Hmm, I just tried re-producing, but I wasn't able to. This worked fine for me :/

**Comment by pabeln** [comment]
Thanks for responding. 

Does it matter if I have the plugin (jquery-bridget & isotope-layout) in devDependencies or Dependencies on my package.json?

**Comment by desandro** [comment]
That shouldn't matter.

**Comment by pabeln** [comment]
Ok I fixed this by moving the jquery.bridget.js file to a local folder (/scripts/vendor/) and referenced that instead of letting Browserify manage it:

This did not work
`var bridget = require('jquery-bridget');`

But this did
`var bridget = require('./vendor/jquery.bridget.js');`

Not sure why this worked. Hope it helps someone else.

**Comment by hirasso** [comment]
Same Problem here... Same solution worked for me as well. The problem occured after running `npm update`.

**Comment by daskruegge** [comment]
I'm also facing the same issue. 
```
require('jquery-bridget');
var Masonry = require('masonry-layout');
// make Masonry a jQuery plugin
$.bridget( 'masonry', Masonry );
```
does not work (`TypeError: $.bridget is not a function`)
but 
```
require('../../node_modules/jquery-bridget/jquery.bridget');
var Masonry = require('masonry-layout');
// make Masonry a jQuery plugin
$.bridget( 'masonry', Masonry );
```
does work.

**Comment by giannif** [comment]
Had the same bug. Deleting `node_modules` and reinstalling fixed it. It seemed like `jquery.bridge` and my own source code referenced two different `jquery` objects. If it happens again, I'll try to dig in more. I'm using `browserify 13.0.0`.

**Comment by giannif** [comment]
This seems to happen consistently with `yarn`. I can't `yarn` my project that contains `jquery-bridget`. I get `TypeError: $.bridget is not a function` consistently. If I remove my node_modules and `npm i`, it works most of the time. I'm on `2.0.1`. Important thing to note is that jquery-bridget is in a shared directory and is referenced from the main project using webpack aliases. Or maybe it's not important, since I had the same issue with browserify in the comment above
