### ISSUE TITLE
Bump version for Bower caches?

### ISSUE THREAD

**Issue by adjohnson916** [desandro/jquery-bridget#7]
Bower has tag v1.1.0 cached as commit c0df1de29766db7bfca1298a747c7c0e434d0a5d (see the `bower_components/jquery-bridget/.bower.json` property `_resolution.commit` after installing.
But GitHub is saying that tag's commit is a59a27bc573ade95fc8c21925bbd4450f6915b8b.

I'm not sure if that was ever updated through a force push, but hopefully that wouldn't happen often, as changing tags violates ecosystem assumptions.

Luckily Bower still installs the repo, but some tooling I'm building needs to know the actual current tag commit in order to generate links to files, e.g. 
https://raw.githubusercontent.com/desandro/jquery-bridget/c0df1de29766db7bfca1298a747c7c0e434d0a5d/jquery.bridget.js.

I tried `bower cache clear` as suggested in bower/bower#994, but no luck.

Can you bump to version v1.1.1 so Bower is in sync again? Thanks.

**Comment by desandro** [comment]
I wasn't able to reproduce this bug. `bower install jquery-bridget` installs v1.1.0 with changes from SHA: a59a27bc573ade95fc8c21925bbd4450f6915b8b. SHA c0df1de29766db7bfca1298a747c7c0e434d0a5d is [not a jquery-bridget commit SHA](https://github.com/desandro/jquery-bridget/commit/c0df1de29766db7bfca1298a747c7c0e434d0a5d).

**Comment by adjohnson916** [comment]
@desandro, I wonder if it was previously a commit - do you or any contributors ever force push tags? Odd how Bower seems to have come up with this.
